version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: octofit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./octofit-tracker/backend
    container_name: backend_service
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:your_password@db:5432/octofit_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./octofit-tracker/frontend
    container_name: frontend_service
    restart: always
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: